import type { AudioBlock } from "../blocks/audio.js";
import type { BookmarkBlock } from "../blocks/bookmark.js";
import type { BreadcrumbBlock } from "../blocks/breadcrumb.js";
import type { BulletedListBlock } from "../blocks/bulletedList.js";
import type { BulletedListItemBlock } from "../blocks/bulletedListItem.js";
import type { CalloutBlock } from "../blocks/callout.js";
import type { ChildDatabaseBlock } from "../blocks/childDatabase.js";
import type { ChildPageBlock } from "../blocks/childPage.js";
import type { CodeBlock } from "../blocks/code.js";
import type { ColumnBlock } from "../blocks/column.js";
import type { ColumnListBlock } from "../blocks/columnList.js";
import type { DividerBlock } from "../blocks/divider.js";
import type { EmbedBlock } from "../blocks/embed.js";
import type { EquationBlock } from "../blocks/equation.js";
import type { FileBlock } from "../blocks/file.js";
import type { Heading1Block } from "../blocks/heading1.js";
import type { Heading2Block } from "../blocks/heading2.js";
import type { Heading3Block } from "../blocks/heading3.js";
import type { ImageBlock } from "../blocks/image.js";
import type { LinkPreviewBlock } from "../blocks/linkPreview.js";
import type { LinkToPageBlock } from "../blocks/linkToPage.js";
import type { NumberedListBlock } from "../blocks/numberedList.js";
import type { NumberedListItemBlock } from "../blocks/numberedListItem.js";
import type { ParagraphBlock } from "../blocks/paragraph.js";
import type { PdfBlock } from "../blocks/pdf.js";
import type { QuoteBlock } from "../blocks/quote.js";
import type { SyncedBlockBlock } from "../blocks/syncedBlock.js";
import type { TableBlock } from "../blocks/table.js";
import type { TableOfContentsBlock } from "../blocks/tableOfContents.js";
import type { TableRowBlock } from "../blocks/tableRow.js";
import type { TemplateBlock } from "../blocks/template.js";
import type { ToDoBlock } from "../blocks/toDo.js";
import type { ToggleBlock } from "../blocks/toggle.js";
import type { UnsupportedBlock } from "../blocks/unsupported.js";
import type { VideoBlock } from "../blocks/video.js";

export type BlockMapper = Partial<{
  audio: AudioBlock;
  bookmark: BookmarkBlock;
  breadcrumb: BreadcrumbBlock;
  bulleted_list: BulletedListBlock;
  bulleted_list_item: BulletedListItemBlock;
  callout: CalloutBlock;
  child_database: ChildDatabaseBlock;
  child_page: ChildPageBlock;
  code: CodeBlock;
  column: ColumnBlock;
  column_list: ColumnListBlock;
  divider: DividerBlock;
  embed: EmbedBlock;
  equation: EquationBlock;
  file: FileBlock;
  heading_1: Heading1Block;
  heading_2: Heading2Block;
  heading_3: Heading3Block;
  image: ImageBlock;
  link_preview: LinkPreviewBlock;
  link_to_page: LinkToPageBlock;
  numbered_list: NumberedListBlock;
  numbered_list_item: NumberedListItemBlock;
  paragraph: ParagraphBlock;
  pdf: PdfBlock;
  quote: QuoteBlock;
  synced_block: SyncedBlockBlock;
  table: TableBlock;
  table_of_contents: TableOfContentsBlock;
  table_row: TableRowBlock;
  template: TemplateBlock;
  to_do: ToDoBlock;
  toggle: ToggleBlock;
  unsupported: UnsupportedBlock;
  video: VideoBlock;
}>;
