import type { AudioBlock } from "../block/audio";
import type { BookmarkBlock } from "../block/bookmark";
import type { BreadcrumbBlock } from "../block/breadcrumb";
import type { BulletedListBlock } from "../block/bulletedList";
import type { BulletedListItemBlock } from "../block/bulletedListItem";
import type { CalloutBlock } from "../block/callout";
import type { ChildDatabaseBlock } from "../block/childDatabase";
import type { ChildPageBlock } from "../block/childPage";
import type { CodeBlock } from "../block/code";
import type { ColumnBlock } from "../block/column";
import type { ColumnListBlock } from "../block/columnList";
import type { DividerBlock } from "../block/divider";
import type { EmbedBlock } from "../block/embed";
import type { EquationBlock } from "../block/equation";
import type { FileBlock } from "../block/file";
import type { Heading1Block } from "../block/heading1";
import type { Heading2Block } from "../block/heading2";
import type { Heading3Block } from "../block/heading3";
import type { ImageBlock } from "../block/image";
import type { LinkPreviewBlock } from "../block/linkPreview";
import type { LinkToPageBlock } from "../block/linkToPage";
import type { NumberedListBlock } from "../block/numberedList";
import type { NumberedListItemBlock } from "../block/numberedListItem";
import type { ParagraphBlock } from "../block/paragraph";
import type { PdfBlock } from "../block/pdf";
import type { QuoteBlock } from "../block/quote";
import type { SyncedBlockBlock } from "../block/syncedBlock";
import type { TableBlock } from "../block/table";
import type { TableOfContentsBlock } from "../block/tableOfContents";
import type { TableRowBlock } from "../block/tableRow";
import type { TemplateBlock } from "../block/template";
import type { ToDoBlock } from "../block/toDo";
import type { ToggleBlock } from "../block/toggle";
import type { UnsupportedBlock } from "../block/unsupported";
import type { VideoBlock } from "../block/video";

export type BlockMapper = Partial<{
  audio: AudioBlock;
  bookmark: BookmarkBlock;
  breadcrumb: BreadcrumbBlock;
  bulleted_list: BulletedListBlock;
  bulleted_list_item: BulletedListItemBlock;
  callout: CalloutBlock;
  child_database: ChildDatabaseBlock;
  child_page: ChildPageBlock;
  code: CodeBlock;
  column: ColumnBlock;
  column_list: ColumnListBlock;
  divider: DividerBlock;
  embed: EmbedBlock;
  equation: EquationBlock;
  file: FileBlock;
  heading_1: Heading1Block;
  heading_2: Heading2Block;
  heading_3: Heading3Block;
  image: ImageBlock;
  link_preview: LinkPreviewBlock;
  link_to_page: LinkToPageBlock;
  numbered_list: NumberedListBlock;
  numbered_list_item: NumberedListItemBlock;
  paragraph: ParagraphBlock;
  pdf: PdfBlock;
  quote: QuoteBlock;
  synced_block: SyncedBlockBlock;
  table: TableBlock;
  table_of_contents: TableOfContentsBlock;
  table_row: TableRowBlock;
  template: TemplateBlock;
  to_do: ToDoBlock;
  toggle: ToggleBlock;
  unsupported: UnsupportedBlock;
  video: VideoBlock;
}>;
